services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: moodle_dev_db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    restart: unless-stopped


  moodle-app:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodle_dev_app
    user: root
    ports:
      - '8080:80' 
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD= 
    volumes:
      - ./moodle_src:/var/www/html
      - moodledata_data:/var/www/moodledata
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  mariadb_data:
  moodledata_data: